name: Dev to Prod Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./node

      - name: Run tests
        run: npm test
        working-directory: ./node

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: test
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to Dev
        run: echo "Deploying to DEV"

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Use secret safely
        run: echo "Using secret securely"
        env:
          PASSWORD: ${{ secrets.MY_PASSWORD }}

      - name: Deploy to Prod
        run: echo "Deploying to PROD"
