name: Node CI Using Reusable Template

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable-node.yml
    with:
      node-version: "20"
      app-path: "./node"
  
         
       
      
            
